#
# CAUTION: This file is automatically generated by PetaLinux SDK
#

TEXT_BASE = 0x80100000
CONFIG_SYS_TEXT_BASE = 0x80100000

PLATFORM_CPPFLAGS += -mxl-barrel-shift
PLATFORM_CPPFLAGS += -mno-xl-soft-div
PLATFORM_CPPFLAGS += -mxl-pattern-compare
PLATFORM_CPPFLAGS += -mhard-float
PLATFORM_CPPFLAGS += -mxl-multiply-high
PLATFORM_CPPFLAGS += -mno-xl-soft-mul
PLATFORM_CPPFLAGS += -mcpu=v11.0
PLATFORM_CPPFLAGS += -fgnu89-inline
